# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-12 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20180412_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='desc',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='城市描述'),
        ),
        migrations.AlterField(
            model_name='courseorg',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.Cities', verbose_name='所在城市'),
        ),
        migrations.AlterField(
            model_name='courseorg',
            name='image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='org/%Y/%m', verbose_name='描述图片'),
        ),
    ]
