# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-15 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_auto_20180414_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='/media/teacher/%Y/%m', verbose_name='头像'),
        ),
    ]
