# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-21 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_auto_20180418_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='tag',
            field=models.CharField(blank=True, default='学术一流', max_length=10, null=True, verbose_name='机构标签'),
        ),
    ]
