# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-19 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0006_auto_20180419_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavorite',
            name='fav_type',
            field=models.CharField(blank=True, choices=[('o', '机构'), ('c', '课程'), ('t', '老师')], max_length=1, null=True, verbose_name='收藏类型'),
        ),
    ]
