# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-19 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0007_auto_20180419_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavorite',
            name='fav_type',
            field=models.IntegerField(default=0, verbose_name='收藏类型'),
        ),
    ]
