# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-19 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0008_auto_20180419_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavorite',
            name='fav_type',
            field=models.IntegerField(choices=[(1, '课程'), (2, '机构'), (3, '老师')], default=1, verbose_name='收藏类型'),
        ),
    ]
