# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-16 18:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_auto_20180416_1827'),
        ('courses', '0005_auto_20180415_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.Teacher', verbose_name='课程老师'),
        ),
    ]
