# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-16 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_tag',
        ),
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='课程类别'),
        ),
    ]
