# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-18 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180412_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='image',
            field=models.ImageField(default='/images/default.png', upload_to='images/%Y/%m', verbose_name='头像'),
        ),
    ]
