# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-19 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180419_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_type',
            field=models.CharField(choices=[('register', '注册'), ('forget', '找回密码'), ('email_update', '邮箱修改')], max_length=20, verbose_name='验证码类型'),
        ),
    ]
