# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-19 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180419_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='mobile',
            field=models.CharField(default='', max_length=11, verbose_name='手机号'),
        ),
    ]
